version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
